'use strict';
/* ===== Ocean Campaign: twelve islands, each guarded by a boss fish. Breed the exact fish it demands to move on. ===== */

const CAMPAIGN = [
  { n: 'Lilypad Pond', color: '#5aa84a', pos: [56, 262], bg: 'bg_forest', boss: { n: 'Old Gill', t: 'the Pond King', sp: 'goldfish', mods: [], big: 1.9, taunt: 'Nobody out-swims me in MY pond! Come back with a goldfish that has real racing stripes.' }, spec: { sp: 'goldfish', mods: ['striped'] }, reward: { money: 2500, rp: 3, items: { mut1: 2 }, perks: [['growth', 0.02, '+2% growth in every tank']] } },
  { n: 'Whisker Creek', color: '#7ac060', pos: [128, 230], bg: 'bg_forest', boss: { n: 'Duchess Fin', t: 'of the Creek', sp: 'betta', mods: ['pearl'], big: 1.8, taunt: 'A pearl-spotted betta? Ha! Show me one and I might let you cross.' }, spec: { sp: 'betta', mods: ['pearl', 'spotted'] }, reward: { money: 7000, rp: 4, items: { mut1: 3 }, perks: [['value', 0.02, '+2% fish value']] } },
  { n: 'Mirror Lake', color: '#6ad0f0', pos: [64, 176], bg: 'bg_sunset', boss: { n: 'The Silver Matron', t: 'Lady of the Lake', sp: 'angelfish', mods: ['frosty'], big: 1.8, taunt: 'Only gold impresses me. Bring a golden angelfish.' }, spec: { sp: 'angelfish', mods: ['golden'] }, reward: { money: 18000, rp: 5, items: { mut2: 2 }, perks: [['mod', 0.05, '+5% modifier chance']] } },
  { n: 'Thunder Falls', color: '#8ac8d8', pos: [140, 150], bg: 'bg_forest', boss: { n: 'Baron von Discus', t: 'Lord of the Falls', sp: 'discus', mods: ['electric'], big: 1.7, taunt: 'The falls thunder for me alone. Frost and stripes, little breeder — frost and stripes.' }, spec: { sp: 'discus', mods: ['frosty', 'striped'] }, reward: { money: 45000, rp: 6, items: { mut2: 3 }, perks: [['cust', 0.06, 'customers arrive 6% faster']] } },
  { n: 'Coral Gate', color: '#ff8aa8', pos: [70, 96], bg: 'bg_reef', boss: { n: 'Madame Mandarin', t: 'Keeper of the Gate', sp: 'mandarin', mods: ['neon'], big: 1.9, taunt: 'The gate opens only for the dazzling. Neon and pearl, darling.' }, spec: { sp: 'mandarin', mods: ['neon', 'pearl'] }, reward: { money: 110000, rp: 8, items: { mut3: 1 }, perks: [['exp', 0.06, 'boats sail 6% faster']] } },
  { n: 'Lion Reef', color: '#ff6a5a', pos: [150, 60], bg: 'bg_reef', boss: { n: 'Spike the Corsair', t: 'Terror of the Reef', sp: 'lionfish', mods: ['fiery'], big: 1.8, taunt: 'Spikes, sparks and stripes! Anything less and I eat you.' }, spec: { sp: 'lionfish', mods: ['electric', 'striped', 'spotted'] }, reward: { money: 260000, rp: 10, items: { mut3: 2 }, perks: [['show', 0.04, 'show scores +4%']] } },
  { n: 'Kelp Throne', color: '#4cc070', pos: [232, 96], bg: 'bg_blue', boss: { n: 'King Idol', t: 'on the Kelp Throne', sp: 'moorish', mods: ['golden'], big: 1.8, taunt: 'Kneel before the golden idol — or bring me a better one.' }, spec: { sp: 'moorish', mods: ['golden', 'pearl', 'candy'] }, reward: { money: 600000, rp: 12, items: { mut3: 3 }, perks: [['growth', 0.03, '+3% growth in every tank']] } },
  { n: 'Thunder Shoals', color: '#e8e060', pos: [236, 164], bg: 'bg_space', boss: { n: 'Emperor Zeus', t: 'Storm-Caller', sp: 'emperor', mods: ['electric', 'glitch'], big: 1.7, taunt: 'The storm obeys me. Prismatic colours and a lightning spark — if you dare.' }, spec: { sp: 'emperor', mods: ['prismatic', 'electric'] }, reward: { money: 1400000, rp: 14, items: { mut4: 1 }, perks: [['value', 0.03, '+3% fish value']] } },
  { n: "Dragon's Trench", color: '#3ad0a0', pos: [312, 206], bg: 'bg_blue', boss: { n: 'Jade Emperor', t: 'the Coiled Dragon', sp: 'jadedragon', mods: ['emerald', 'cosmic'], big: 1.6, taunt: 'A thousand years I have coiled here. Show me stars, gold and lightning on a dragonfish.' }, spec: { sp: 'jadedragon', mods: ['cosmic', 'golden', 'electric'] }, reward: { money: 3500000, rp: 16, items: { mut4: 2 }, perks: [['inherit', 0.05, '+5% modifier inheritance']] } },
  { n: 'Sunken Crown', color: '#f0c840', pos: [352, 134], bg: 'bg_sunset', boss: { n: 'The Drowned King', t: 'Wearer of the Crown', sp: 'hammerhead', mods: ['skeleton', 'ghost'], big: 1.5, taunt: 'Even in death I rule. Bring a hammerhead as radiant as my crown was.' }, spec: { sp: 'hammerhead', mods: ['celestial', 'golden', 'magma'] }, reward: { money: 9000000, rp: 20, items: { mut4: 3 }, perks: [['tier', 0.04, '+4% higher-tier chance']] } },
  { n: 'Abyss Throne', color: '#9a7aff', pos: [300, 64], bg: 'bg_space', boss: { n: 'The Lantern Queen', t: 'of the Abyss', sp: 'anglerfish', mods: ['abyssal', 'glitch'], big: 1.9, taunt: 'Down here only the old bloodlines survive. Generation six or nothing.' }, spec: { sp: 'anglerfish', mods: ['abyssal', 'ghost', 'glitch'], gen: 6 }, reward: { money: 25000000, rp: 25, items: { mut5: 2 }, perks: [['value', 0.04, '+4% fish value']] } },
  { n: "Leviathan's Maw", color: '#ff4a4a', pos: [384, 34], bg: 'bg_space', boss: { n: 'Leviathan', t: 'Devourer of Tides', sp: 'oarfish', mods: ['diamond', 'phoenix', 'cosmic'], big: 2.3, taunt: 'I am the sea. Breed me a marlin with diamond, fire and stars — a true legend — and you may call yourself an admiral.' }, spec: { sp: 'marlin', mods: ['diamond', 'phoenix', 'cosmic'], gen: 8 }, reward: { money: 100000000, rp: 40, items: { mut5: 5 }, perks: [['value', 0.08, '+8% fish value'], ['growth', 0.05, '+5% growth in every tank']], title: 'Admiral of the Seas' } },
];
const campDone = i => !!(S.camp && S.camp.done[i]);
const campCur = () => { let i = 0; while (i < CAMPAIGN.length && campDone(i)) i++; return i; };
function campPerk(key) { let v = 0; if (!S || !S.camp) return 0; CAMPAIGN.forEach((c, i) => { if (S.camp.done[i]) c.reward.perks.forEach(([k, x]) => { if (k === key) v += x; }); }); return v; }
function campMatches(spec, f) { return isAdult(f) && !fishLocked(f) && f.sp === spec.sp && spec.mods.every(m => f.mods.includes(m)) && (f.gen || 0) >= (spec.gen || 0); }
function campCandidates(spec) {
  return S.fish.filter(f => isAdult(f) && !fishLocked(f)).map(f => { const have = spec.mods.filter(m => f.mods.includes(m)), spOk = f.sp === spec.sp; return { f, have, miss: spec.mods.filter(m => !f.mods.includes(m)), spOk, genOk: (f.gen || 0) >= (spec.gen || 0), full: campMatches(spec, f), score: (spOk ? 100 : 0) + have.length * 10 + ((f.gen || 0) >= (spec.gen || 0) ? 1 : 0) }; })
    .filter(c => c.spOk || c.have.length).sort((a, b) => b.score - a.score || fishValue(b.f) - fishValue(a.f));
}
function fightBoss(idx, fid) {
  const c = CAMPAIGN[idx], f = getFish(fid); if (!c || !f) return fail('Missing');
  if (idx > campCur()) return fail('Defeat the previous boss first'); if (campDone(idx)) return fail('You already conquered this island');
  if (!campMatches(c.spec, f)) return fail('That fish does not meet the boss\'s demand');
  S.camp.done[idx] = true; S.money += c.reward.money; S.earned += c.reward.money; gainRP(c.reward.rp);
  for (const k in c.reward.items) S.items[k] = (S.items[k] || 0) + c.reward.items[k];
  f.medals.g++; if (c.reward.title && !S.titles.includes(c.reward.title)) S.titles.push(c.reward.title);
  G.dirty = true; return { ok: true, idx };
}

/* ---------- island models ---------- */
function carve(g, cx, cz, r, y, col) { for (let x = Math.floor(cx - r); x <= Math.ceil(cx + r); x++) for (let z = Math.floor(cz - r); z <= Math.ceil(cz + r); z++) if ((x - cx) ** 2 + (z - cz) ** 2 <= r * r) { for (let yy = y + 1; yy <= y + 4; yy++) g.del(x, yy, z); g.set(x, y, z, typeof col === 'function' ? col(x, z) : col); } }
function grass(g, r, h, a, b) { for (let y = 0; y < h; y++) g.cyl(0, 0, r - y * 0.4, y, y, (x, yy, z) => J(y < h - 1 ? (a || '#8a6a3a') : (b || '#5aa84a'), (hash(x + ',' + z) % 6 === 0 ? -0.08 : 0.02))); }
const CAMP_GLOW = {};
const CAMP_BUILD = [
  g => { shallow(g, 30, '#4fb89a'); grass(g, 22, 3); carve(g, 3, 2, 10, 2, (x, z) => J('#58b0e0', hash(x + ',' + z) % 5 === 0 ? 0.08 : 0)); [[1, 0], [5, 4], [-2, 5], [7, -1], [3, 8]].forEach(([x, z], i) => { g.cyl(x, z, 2.4, 3, 3, '#3f9f4a'); if (i % 2 === 0) g.ell(x, 4, z, 1, 1, 1, '#ff8ac0'); }); for (let i = 0; i < 12; i++) { const a = i * 0.9, x = Math.cos(a) * 13 + 3, z = Math.sin(a) * 13 + 2; g.line([x, 3, z], [x + 0.5, 9 + i % 4, z], '#7ab05a', 0.5); g.ell(x + 0.5, 10 + i % 4, z, 0.8, 1.6, 0.8, '#7a5a2a'); } tree(g, -13, -8, 12, 7, '#5a9a3a'); },
  g => { shallow(g, 30, '#58c08a'); grass(g, 22, 4); for (let t = -22; t <= 22; t++) { const z = Math.sin(t * 0.25) * 6 + t * 0.2; carve(g, t, z, 2.2, 3, '#5ab8e8'); } for (let z = -6; z <= 6; z++) g.box(-1, 4, z + 6, 1, 4, z + 6, '#8a6a3a'); g.box(-1, 5, -1, -1, 5, 14, '#6a4a28'); g.box(1, 5, -1, 1, 5, 14, '#6a4a28'); [[-12, -10], [10, -12], [14, 8], [-14, 10], [0, -14]].forEach(([x, z], i) => { g.cyl(x, z, 1, 4, 14, '#f0f0e8'); g.ell(x, 16, z, 5, 4, 5, i % 2 ? '#c8d850' : '#9ac848'); }); g.ell(8, 5, 4, 3, 2, 3, '#7a8a80'); g.ell(-6, 5, -3, 2.4, 2, 2.4, '#8a9a90'); },
  g => { shallow(g, 30, '#6ad8e0'); grass(g, 22, 3); carve(g, -2, 2, 13, 2, (x, z) => J('#8ad8f8', ((Math.floor(x / 3) + Math.floor(z / 3)) % 2) * 0.05)); for (const [x, z] of [[10, -14], [16, -14], [10, -8], [16, -8]]) g.box(x, 3, z, x + 1, 14, z + 1, '#c0453a'); for (let y = 0; y < 5; y++) g.box(8 + y, 15 + y, -16 + y, 19 - y, 15 + y, -6 - y, '#a8352a'); g.box(9, 3, -15, 18, 3, -7, '#d8c898'); [[4, -10], [6, -6], [8, -3]].forEach(([x, z]) => g.cyl(x, z, 1.6, 3, 3, '#9aa8a8')); tree(g, -16, 8, 11, 6, '#e8a0b8'); },
  g => { shallow(g, 30, '#6ac0d0'); for (let y = 0; y < 16; y++) g.cyl(0, 0, 21 - y * 0.95, y, y, (x, yy, z) => J(y > 14 ? '#5aa84a' : '#8a8478', hash(x + ',' + y + ',' + z) % 5 === 0 ? -0.1 : y * 0.01)); for (let y = 3; y < 16; y++) { const r = 21 - y * 0.95; for (let x = -2; x <= 2; x++) { const z = Math.round(Math.sqrt(Math.max(0, r * r - x * x))); g.set(x, y, z, '#a8e8ff'); g.set(x, y, z + 1, '#d8f8ff'); } } carve(g, 0, 22, 6, 1, '#5ac0f0'); [[-8, -6], [6, -10], [-12, 4], [10, 2], [-3, 8]].forEach(([x, z]) => g.cyl(x, z, 4.4, 15, 26, (X, Y) => J('#2f7a3a', (Y - 15) / 60), 0.4)); const gl = new VGrid(0.02); for (let i = 0; i < 6; i++) gl.set(-2 + (i % 3) * 2, 8 + i, 18 + i % 2, '#ffffff'); CAMP_GLOW[3] = gl.geometry(); },
  g => { shallow(g, 30, '#58d8c8'); g.cyl(0, 0, 22, 0, 1, (x, y, z) => J('#ecdca4', hash(x + ',' + z) % 6 === 0 ? -0.06 : 0.02)); [[-11, 0], [11, 0]].forEach(([x, z]) => { [['#ff7aa0', 4.6, 3], ['#ff9a52', 4, 9], ['#e86ad0', 3.4, 14], ['#ffd25a', 2.6, 18]].forEach(([c, r, y]) => g.ell(x, y, z, r, 3.4, r, (X, Y, Z, dx, dy) => J(c, dy * 0.15))); }); for (let a = 0; a <= 12; a++) { const t = a / 12 * Math.PI, x = Math.cos(t) * 11, y = 19 + Math.sin(t) * 6; g.ell(x, y, 0, 2.6, 2.6, 2.6, (X, Y, Z, dx, dy) => J(['#ff7aa0', '#ffd25a', '#e86ad0'][a % 3], dy * 0.12)); } for (let i = 0; i < 9; i++) { const a = i * 0.7 + 0.4; g.ell(Math.cos(a) * 15, 1, Math.sin(a) * 15 + 3, 1.5, 1, 1.2, '#f8f4e8'); } for (let i = 0; i < 4; i++) { const x = -8 + i * 6, z = 10 + i % 2 * 3; g.box(x - 1, 2, z, x + 1, 2, z, '#e8403a'); g.box(x, 2, z - 1, x, 2, z + 1, '#e8403a'); } },
  g => { shallow(g, 30, '#3a8a8a'); g.cyl(0, 0, 21, 0, 2, (x, y, z) => J('#2a5a6a', hash(x + ',' + z) % 4 === 0 ? 0.08 : -0.02)); for (let i = 0; i < 26; i++) { const a = i * 2.4, r = 3 + (i * 7) % 15, x = Math.cos(a) * r, z = Math.sin(a) * r, h = 6 + (i * 5) % 9; g.cyl(x, z, 1.8, 2, 2 + h, (X, Y) => J(i % 2 ? '#e8403a' : '#f4f0e8', (Y % 3 === 0 ? -0.1 : 0)), 0.2); } g.ell(0, 5, 0, 7, 4, 7, '#3a4a58'); },
  g => { shallow(g, 30, '#3f9f8a'); g.cyl(0, 0, 20, 0, 2, '#4a6a58'); g.box(-7, 2, -6, 7, 8, 6, (x, y, z) => J('#6a7078', hash(x + ',' + y + ',' + z) % 5 === 0 ? -0.1 : 0)); g.box(-7, 9, -6, 7, 26, -3, '#707880'); g.box(-8, 9, -6, -7, 15, 6, '#7a8088'); g.box(7, 9, -6, 8, 15, 6, '#7a8088'); for (let i = 0; i < 9; i++) { const a = i / 8 * Math.PI; g.cyl(-5 + i * 1.25, -4.5, 1.2, 26, 31 + (i % 2 ? 4 : 0), '#f0c030', 0.3); } g.ell(0, 20, -4, 2, 2, 1, '#e8403a'); for (let i = 0; i < 16; i++) { const a = i * 1.6, r = 14 + (i % 3) * 2, x = Math.cos(a) * r, z = Math.sin(a) * r; for (let y = 0; y < 12 + i % 6; y += 2) g.line([x + Math.sin(y * 0.4) * 1.5, y + 1, z], [x + Math.sin((y + 2) * 0.4) * 1.5, y + 3, z], '#4a9a48', 0.8); } },
  g => { shallow(g, 30, '#3a4a6a'); g.cyl(0, 0, 22, 0, 4, (x, y, z) => J('#2e3038', hash(x + ',' + y + ',' + z) % 4 === 0 ? 0.08 : -0.02)); g.cyl(0, 0, 3, 4, 34, '#8a8e96', 1.2); g.cyl(0, 0, 0.6, 34, 40, '#c0c4cc'); [[-6, 36], [0, 38], [7, 35], [14, 37]].forEach(([x, y]) => g.ell(x, y, 0, 9, 4, 8, (X, Y, Z, dx, dy) => J('#4a4e5c', dy * 0.14))); for (let i = 0; i < 6; i++) g.ell(Math.cos(i) * 14, 4, Math.sin(i) * 14, 3, 2, 3, '#3a3c44'); const gl = new VGrid(0.02); gl.line([-2, 34, 0], [0, 40, 0], '#fff7a0', 0.9); gl.line([6, 34, 2], [1, 40, 0], '#ffe860', 0.9); gl.line([-8, 33, 3], [-1, 40, 0], '#fff7a0', 0.7); CAMP_GLOW[7] = gl.geometry(); },
  g => { for (let r = 30; r > 2; r -= 3) g.cyl(0, 0, r, -1, -1, (x, y, z) => J(Math.floor(r / 3) % 2 ? '#10343a' : '#18484e', hash(x + ',' + z) % 9 === 0 ? 0.05 : 0)); for (let t = 0; t < 22; t++) { const a = t * 0.55, r = 14 - t * 0.15, x = Math.cos(a) * r, z = Math.sin(a) * r, y = 1 + t * 0.9, rad = 3.6 - t * 0.08; g.ell(x, y, z, rad, rad, rad, (X, Y, Z, dx, dy) => J(t % 2 ? '#2fae7a' : '#3fcb8a', dy * 0.12 + (hash(X + ',' + Y + ',' + Z) % 4 === 0 ? 0.08 : 0))); } const ha = 21 * 0.55, hx = Math.cos(ha) * 11, hz = Math.sin(ha) * 11, hy = 21; g.ell(hx, hy, hz, 4.6, 3.4, 3.4, '#3fcb8a'); g.line([hx, hy + 3, hz], [hx + 2, hy + 8, hz + 4], '#e8dcb8', 0.9); g.line([hx, hy + 3, hz], [hx - 3, hy + 8, hz - 2], '#e8dcb8', 0.9); const gl = new VGrid(0.02); gl.ell(hx + 3, hy + 1, hz + 2, 1, 1, 1, '#ff3a3a'); gl.ell(hx + 3, hy + 1, hz - 2, 1, 1, 1, '#ff3a3a'); CAMP_GLOW[8] = gl.geometry(); },
  g => { shallow(g, 30, '#58d8c8'); g.cyl(0, 0, 20, 0, 2, (x, y, z) => J('#c8b88a', hash(x + ',' + z) % 5 === 0 ? -0.1 : 0)); g.cyl(0, 0, 13, 3, 6, (x, y) => J('#f0c030', y % 2 ? 0.1 : -0.05)); carve(g, 0, 0, 11, 3, '#58c0b0'); for (let i = 0; i < 9; i++) { const a = i / 9 * 6.28, x = Math.cos(a) * 12, z = Math.sin(a) * 12; g.cyl(x, z, 2.2, 6, 18 + (i % 2) * 4, (X, Y) => J('#f4c838', (Y - 6) / 70), 0.3); g.ell(x, 19 + (i % 2) * 4, z, 1.4, 1.4, 1.4, ['#e8403a', '#3a7ae8', '#3ac860'][i % 3]); } for (let i = 0; i < 8; i++) g.ell(Math.cos(i) * 17, 3, Math.sin(i) * 17, 2, 1.4, 2, '#3a9a5a'); const gl = new VGrid(0.02); gl.ell(0, 5, 0, 2, 2, 2, '#fff2a0'); CAMP_GLOW[9] = gl.geometry(); },
  g => { for (let r = 30; r > 2; r -= 3) g.cyl(0, 0, r, -1, -1, (x, y, z) => J(Math.floor(r / 3) % 2 ? '#241a4a' : '#32246a', hash(x + ',' + z) % 9 === 0 ? 0.06 : 0)); g.cyl(0, 0, 9, 0, 3, '#1a1a24'); g.cyl(0, 0, 7, 3, 30, (x, y, z) => J('#22222e', hash(x + ',' + y + ',' + z) % 5 === 0 ? 0.1 : -0.02), 1.4); for (let i = 0; i < 6; i++) { const a = i * 1.05; g.line([Math.cos(a) * 5, 26, Math.sin(a) * 5], [Math.cos(a) * 16, 4, Math.sin(a) * 16], '#4a3a7a', 0.9); } const gl = new VGrid(0.02); gl.ell(0, 34, 0, 4, 4, 4, '#80fff0'); gl.line([0, 30, 0], [0, 28, 0], '#40c0b0', 0.5); gl.ell(0, 33, 4, 1, 1, 1, '#ffffff'); for (let i = 0; i < 8; i++) gl.set(Math.cos(i) * 20, 3 + i % 3, Math.sin(i) * 20, '#80fff0'); CAMP_GLOW[10] = gl.geometry(); },
  g => { for (let r = 32; r > 2; r -= 3) g.cyl(0, 0, r, -1, -1, (x, y, z) => J(Math.floor(r / 3) % 2 ? '#2a0a0e' : '#4a1018', hash(x + ',' + z) % 9 === 0 ? 0.08 : 0)); const bone = (x, y, z) => J('#ece4d0', hash(x + ',' + y + ',' + z) % 5 === 0 ? -0.1 : 0.02); for (const zz of [-8, 8]) { for (let t = 0; t <= 20; t++) { const a = t / 20 * Math.PI, x = Math.cos(a) * 24, y = Math.sin(a) * 30; g.ell(x, y, zz, 2.4, 2.6, 2.4, bone); } for (let i = 0; i < 9; i++) { const x = -20 + i * 5, a = Math.acos(Math.max(-1, Math.min(1, x / 24))); const y = Math.sin(a) * 30; g.cyl(x, zz, 1.4, y - 7, y - 1, bone, 0.2); } } g.box(-6, 0, -9, 6, 8, 9, '#2a1a1a'); g.ell(0, 14, 0, 7, 6, 8, bone); const gl = new VGrid(0.02); gl.ell(-3, 15, 6, 1.4, 1.4, 1.4, '#ff2a2a'); gl.ell(3, 15, 6, 1.4, 1.4, 1.4, '#ff2a2a'); gl.ell(0, 3, 0, 4, 2, 4, '#ff5a2a'); CAMP_GLOW[11] = gl.geometry(); },
];
function campGeo(i) { return shopGeo('camp' + i, CAMP_BUILD[i]); }
function campIcon(i, px) { const s = px * 2, url = renderThumb('camp' + i + s, s, s, () => { const g = new THREE.Group(); g.add(new THREE.Mesh(campGeo(i), plainMat())); if (CAMP_GLOW[i]) g.add(new THREE.Mesh(CAMP_GLOW[i], glowMat())); return g; }, ISO_DIR, 0.06); return `<img src="${url}" style="width:${px}px;height:${px}px;object-fit:contain" alt="" draggable="false">`; }
const CAMP_S = 0.95;
function flagGeo() { return shopGeo('campflag', g => { g.cyl(0, 0, 0.8, 0, 22, '#e8e0d0'); g.box(1, 15, 0, 11, 22, 0, '#f0c030'); g.box(3, 17, 0, 9, 20, 0, '#e8403a'); }); }

class CampScene extends ExpScene {
  mapBox() { return new THREE.Box3(new THREE.Vector3(0, -6, -6), new THREE.Vector3(MAP.W + 16, 56, MAP.D + 4)); }
  build() { this.buildOcean(); this.buildCamp(); }
  buildCamp() {
    const sc = this.scene, mat = plainMat(); this.fogs = []; this.flags = []; this.dashes = [];
    CAMPAIGN.forEach((c, i) => {
      const m = new THREE.Mesh(campGeo(i), mat); m.position.set(c.pos[0], 0, c.pos[1]); m.scale.setScalar(CAMP_S); sc.add(m);
      if (CAMP_GLOW[i]) { const gm = new THREE.Mesh(CAMP_GLOW[i], glowMat()); gm.position.copy(m.position); gm.scale.setScalar(CAMP_S); sc.add(gm); }
      const hit = new THREE.Mesh(new THREE.CylinderGeometry(30 * CAMP_S, 30 * CAMP_S, 44, 10), new THREE.MeshBasicMaterial({ visible: false })); hit.position.set(c.pos[0], 10, c.pos[1]); hit.userData.loc = 'c' + i; sc.add(hit); this.hits.push(hit);
      const fog = new THREE.Group(); for (let k = 0; k < 6; k++) { const b = new THREE.Mesh(new THREE.BoxGeometry(16 + (k % 3) * 5, 11, 14 + (k % 2) * 5), new THREE.MeshBasicMaterial({ color: 0xcfd8e4, transparent: true, opacity: 0.88 })); b.position.set((k - 2.5) * 6, 6 + (k % 3) * 4, ((k * 7) % 5 - 2) * 5); fog.add(b); } fog.scale.setScalar(0.8); fog.position.set(c.pos[0], 4, c.pos[1]); sc.add(fog); this.fogs.push(fog);
      const fl = new THREE.Mesh(flagGeo(), mat); fl.position.set(c.pos[0] + 10, 16, c.pos[1] - 6); fl.scale.setScalar(1.3); fl.visible = false; sc.add(fl); this.flags.push(fl);
    });
    for (let i = 0; i < CAMPAIGN.length - 1; i++) { const a = CAMPAIGN[i].pos, b = CAMPAIGN[i + 1].pos, n = Math.floor(Math.hypot(b[0] - a[0], b[1] - a[1]) / 9), row = []; for (let k = 1; k < n; k++) { const t = k / n; if (t < 0.22 || t > 0.78) continue; const d = new THREE.Mesh(new THREE.BoxGeometry(3.6, 1.4, 3.6), new THREE.MeshBasicMaterial({ color: 0xffffff })); d.position.set(a[0] + (b[0] - a[0]) * t, 0, a[1] + (b[1] - a[1]) * t); sc.add(d); row.push(d); } this.dashes.push(row); }
    this.ring = null;
  }
  syncBoats() {
    const cur = campCur(), sig = cur + '|' + CAMPAIGN.map((c, i) => (campDone(i) ? 1 : 0)).join('');
    if (sig !== this.csig) {
      this.csig = sig;
      this.fogs.forEach((f, i) => (f.visible = i > cur)); this.flags.forEach((f, i) => (f.visible = campDone(i)));
      this.dashes.forEach((row, i) => row.forEach(d => d.material.color.set(campDone(i) ? 0xffd23a : i === cur ? 0xffffff : 0x6a8aa8)));
    }
    this.fogs.forEach((f, i) => { f.position.y = 4 + Math.sin(this.t * 0.8 + i) * 0.8; });
  }
  overlay(ctx) {
    const cv = this.cv, k = cv.height / 640, cur = campCur(); ctx.textAlign = 'center'; ctx.textBaseline = 'middle';
    const tag = (txt, x, y, col, bold) => { ctx.font = `${bold ? 700 : 600} ${Math.round(13 * k)}px "Segoe UI", system-ui, sans-serif`; const w = ctx.measureText(txt).width + 14 * k, h = 20 * k; ctx.fillStyle = 'rgba(8,20,34,0.86)'; ctx.beginPath(); if (ctx.roundRect) ctx.roundRect(x - w / 2, y - h / 2, w, h, 6 * k); else ctx.rect(x - w / 2, y - h / 2, w, h); ctx.fill(); ctx.strokeStyle = col; ctx.lineWidth = 1.5 * k; ctx.stroke(); ctx.fillStyle = '#eef6ff'; ctx.fillText(txt, x, y + 0.5); };
    CAMPAIGN.forEach((c, i) => {
      const p = this.proj(c.pos[0], 48, c.pos[1]), lock = i > cur, done = campDone(i), sel = UI.campSel === i;
      if (sel) { const q = this.proj(c.pos[0], 0, c.pos[1]), pr = Math.abs(this.proj(c.pos[0] + 32 * CAMP_S, 0, c.pos[1])[0] - q[0]) * 1.05, pulse = 1 + 0.04 * Math.sin(this.t * 4); ctx.save(); ctx.strokeStyle = '#ffe27a'; ctx.lineWidth = 3 * k; ctx.shadowColor = '#ffcf40'; ctx.shadowBlur = 12 * k; ctx.setLineDash([9 * k, 6 * k]); ctx.lineDashOffset = -this.t * 40; ctx.beginPath(); ctx.ellipse(q[0], q[1], pr * pulse, pr * 0.62 * pulse, 0, 0, 6.3); ctx.stroke(); ctx.restore(); }
      tag(lock ? `🔒 ${i + 1}. ???` : `${done ? '✔' : '⚔'} ${i + 1}. ${c.n}`, p[0], p[1], lock ? '#6a7a8c' : done ? '#4fe0a0' : sel ? '#ffe27a' : '#ff9a6a', sel || (!done && i === cur));
    });
  }
}
TANK_DIM3.arena = [170, 112, 96]; TANK_DIM3.arena_s = [170, 112, 96];
TANK_TYPE.arena = { id: 'arena', n: 'Arena', w: 'fresh', base: 5, cap: 9, price: 0, lvl: 99, mult: 1 }; TANK_TYPE.arena_s = { id: 'arena_s', n: 'Arena', w: 'salt', base: 5, cap: 9, price: 0, lvl: 99, mult: 1 };
SKIN.arena = { id: 'arena', n: 'Arena', price: 0, gravel: '#b8a888', frame: '#3a2a2a', b: {} };
class BossScene extends TankScene3D {
  constructor(canvas, idx) {
    const c = CAMPAIGN[idx], salt = SPECIES[c.spec.sp].w === 'salt';
    super(canvas, { id: 'boss' + idx, type: salt ? 'arena_s' : 'arena', bg: c.bg, skin: 'arena', slots: [salt ? 'seafan' : 'sword', 'dragonstone', 'chest', 'bubbles'], up: {}, wq: 100, fedUntil: 0 }, true, null, null);
    this.idx = idx; this.vf = null;
  }
  fishList() { const b = CAMPAIGN[this.idx].boss; if (!this.vf) this.vf = [{ id: 'boss', sp: b.sp, mods: b.mods, g: 1, vb: 0, loc: 'arena', fav: false, big: b.big, name: b.n }]; return this.vf; }
}

/* ---------- UI ---------- */
const modByLoc = m => (MODS[m].exp ? `Found on expeditions (${LOCATION[MODS[m].exp].n})` : MODS[m].ev ? 'Seasonal event modifier' : `${MOD_TIER_NAMES[MODS[m].t]} modifier`);
function bossRewardText(c) { const r = c.reward, items = Object.entries(r.items).map(([k, v]) => `${v}× ${CONSUMABLE[k].n}`).join(', '); return `<div class="stats">${pill('Money', fmt(r.money))}${pill('Research', '🔬 ' + r.rp + ' RP')}${pill('Items', items)}</div><div class="small good">Permanent: ${r.perks.map(p => p[2]).join(' · ')}${r.title ? ' · Title “' + r.title + '”' : ''}</div>`; }
function viewCampaign() {
  const cur = campCur(), done = CAMPAIGN.filter((c, i) => campDone(i)).length;
  if (UI.campSel == null || UI.campSel > cur) UI.campSel = Math.min(cur, CAMPAIGN.length - 1);
  const idx = Math.min(UI.campSel, CAMPAIGN.length - 1), c = CAMPAIGN[idx], conquered = campDone(idx), locked = idx > cur;
  let h = pageHead('Ocean Campaign', 'Sail the archipelago of legends. Every island is ruled by a boss fish that will only step aside for the exact fish it demands: breed the right species with the right modifiers, then challenge it.', `${pill('Islands conquered', done + '/' + CAMPAIGN.length)}${pill('Perks', 'value +' + Math.round(campPerk('value') * 100) + '% · growth +' + Math.round(campPerk('growth') * 100) + '%')}`);
  h += `<div class="expwrap"><div><div class="scenewrap" style="position:relative"><canvas class="campscene"></canvas>${zoomCtl(false, true)}</div></div><aside class="exppanel">`;
  h += `<div class="row" style="align-items:flex-start;gap:12px"><div class="locpic">${locked ? '<div class="q" style="font-size:44px;text-align:center;line-height:96px;color:var(--faint)">?</div>' : campIcon(idx, 96)}</div><div class="grow"><div class="dim small">Island ${idx + 1} of ${CAMPAIGN.length}</div><div style="font-size:18px;font-weight:700">${locked ? '???' : c.n}</div><div style="margin-top:4px">${conquered ? '<span class="chip m1">✔ Conquered</span>' : locked ? '<span class="chip m4">🔒 Shrouded in fog</span>' : '<span class="chip m3">⚔ Boss awaits</span>'}</div></div></div>`;
  if (locked) return h + `<p class="dim" style="margin-top:12px">Defeat the boss of <b>${CAMPAIGN[cur].n}</b> first to lift the fog.</p></aside></div>` + campProgressList(cur);
  h += `<div class="bosswrap" style="margin-top:12px"><canvas class="tankscene bossscene" data-idx="${idx}"></canvas></div><div style="margin-top:6px"><b>${c.boss.n}</b> <span class="dim">${c.boss.t}</span></div><div class="small dim" style="font-style:italic;margin:2px 0 10px">“${c.boss.taunt}”</div>`;
  const sp = SPECIES[c.spec.sp];
  h += `<div class="dim small" style="margin-bottom:6px">The boss demands</div><div class="demand"><div class="dpic">${fishSVG(sp.id, c.spec.mods, 86)}</div><div class="grow"><b>${sp.n}</b> ${tierBadge(sp.t)} ${waterTag(sp.w)}<div style="margin:4px 0">${c.spec.mods.map(m => `<span class="chip m${MODS[m].t}" title="${esc(modByLoc(m))}">${MODS[m].icon} ${MODS[m].n}</span>`).join('')}${c.spec.gen ? `<span class="chip m1">Generation ${c.spec.gen}+</span>` : ''}</div><div class="small dim">${c.spec.mods.some(m => MODS[m].exp) ? '⛵ ' + c.spec.mods.filter(m => MODS[m].exp).map(modByLoc).join(', ') : 'All modifiers can be bred into a line.'}</div></div></div>`;
  if (!conquered) {
    const cands = campCandidates(c.spec), full = cands.filter(x => x.full);
    h += `<div class="dim small" style="margin:12px 0 6px">${full.length ? 'Your fish that meet the demand' : cands.length ? 'Closest fish you own' : 'You own no fish of this kind yet'}</div>`;
    if (!cands.length) h += `<div class="empty">Hatch or breed a ${sp.n} and give it the required modifiers.</div>`;
    cands.slice(0, 4).forEach(x => { h += `<div class="item"><div style="width:84px">${fishPic(x.f, 80)}</div><div class="grow">${fishTitle(x.f)}<div class="small">${x.full ? '<span class="good">Meets every requirement!</span>' : `<span class="badc">Missing: ${[...(x.spOk ? [] : [sp.n]), ...x.miss.map(m => MODS[m].n), ...(x.genOk ? [] : ['generation ' + c.spec.gen + '+'])].join(', ')}</span>`}</div></div>${x.full ? btn('Challenge!', 'bossFight', { x: idx, y: x.f.id }, 'pri sm') : btn('Breed', 'breedWith', { x: x.f.id }, 'sm')}</div>`; });
  }
  h += `<div class="dim small" style="margin:12px 0 6px">Reward</div>${bossRewardText(c)}</aside></div>`;
  return h + campProgressList(cur);
}
function campProgressList(cur) { return `<h3>The road ahead</h3><div class="campstrip">${CAMPAIGN.map((c, i) => `<div class="cstep ${campDone(i) ? 'done' : i === cur ? 'cur' : 'lock'} ${UI.campSel === i ? 'sel' : ''}" ${i <= cur ? `data-act="campSel" data-x="${i}"` : ''}><span class="n">${campDone(i) ? '✔' : i + 1}</span>${i > cur ? '???' : c.n}</div>`).join('')}</div>`; }
function bossWinModal(idx, fid) {
  const c = CAMPAIGN[idx], f = getFish(fid), r = c.reward;
  return `<h2>⚔ ${c.n}</h2><div class="duel"><div class="side a">${f ? fishPic(f, 190) : ''}<b>${f ? esc(f.name) : ''}</b></div><div class="vs">VS</div><div class="side b">${fishSVG(c.boss.sp, c.boss.mods, 190)}<b>${c.boss.n}</b></div></div><h2 class="victory">VICTORY!</h2><p class="dim" style="text-align:center">${c.boss.n} bows to your ${f ? esc(fishName(f)) : 'champion'}. The fog lifts from the next island.</p>${bossRewardText(c)}<div class="row" style="margin-top:14px">${btn(idx + 1 < CAMPAIGN.length ? 'On to the next island' : 'Claim your legend', 'campNext', { x: idx + 1 }, 'pri')}${btn('Close', 'closeModal')}</div>`;
}
